#
# Makefile for fujitsu f11eif devices that really don't fit anywhere else.
#

obj-$(CONFIG_FUJITSU_EIFFEL_PROXIMITY) += proximity.o
obj-$(CONFIG_FUJITSU_EIFFEL_ILLUMI) += light.o

obj-y += fcsmd/
obj-y += fcfd/
obj-y += compass/
obj-y += i2cuart/
obj-y += walkmotion/
obj-y += pipe/
obj-y += irda/
obj-y += memread/
obj-y += keypad/
obj-$(CONFIG_FUJITSU_F11EIF_STSCHK) += stschk/
